plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
  NewCops: enable

Layout/LineLength:
  Max: 130
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpecRails/InferredSpecType:
  Enabled: false
